services:
  - type: web
    name: selfmail
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn selfmail.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: selfmail
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

