# Generated by Django 4.2.4 on 2023-08-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfMailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mail', models.EmailField(help_text='The sender of the mail.', max_length=254)),
                ('to_mail', models.EmailField(help_text='The receiver of the mail', max_length=254)),
                ('subject', models.CharField(help_text='The heading of the mail', max_length=500)),
                ('file', models.FileField(help_text='A pdf you want to send.', upload_to='')),
                ('description', models.TextField(help_text='The description/mail')),
            ],
            options={
                'verbose_name': 'SelfMail',
                'verbose_name_plural': 'SelfMail',
            },
        ),
    ]
