# Generated by Django 4.2.4 on 2023-08-15 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmailmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selfmailmodel',
            name='file',
            field=models.FileField(blank=True, help_text='A pdf you want to send.', null=True, upload_to='media/'),
        ),
    ]
