# Generated by Django 4.2.4 on 2023-08-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0002_selfmailmodel_date_created_alter_selfmailmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmailmodel',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='selfmailmodel',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='selfmailmodel',
            name='file',
            field=models.FileField(blank=True, help_text='A pdf you want to send.', null=True, upload_to=''),
        ),
    ]
