# Generated by Django 4.2.4 on 2023-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0003_selfmailmodel_footer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderAndFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, help_text='The header', null=True, upload_to='')),
                ('footer_image', models.ImageField(blank=True, help_text='The footer', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'header_and_footer',
                'verbose_name_plural': 'header_and_footer',
            },
        ),
        migrations.RemoveField(
            model_name='selfmailmodel',
            name='footer_image',
        ),
        migrations.RemoveField(
            model_name='selfmailmodel',
            name='header_image',
        ),
    ]
