# Generated by Django 4.2.4 on 2023-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0004_headerandfooter_remove_selfmailmodel_footer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerandfooter',
            name='footer_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerandfooter',
            name='header_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headerandfooter',
            name='footer_image',
            field=models.ImageField(blank=True, default='footer_image.jpeg', help_text='The footer', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='headerandfooter',
            name='header_image',
            field=models.ImageField(blank=True, default='header_image.jpeg', help_text='The header', null=True, upload_to=''),
        ),
    ]
