# Generated by Django 4.2.4 on 2023-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0005_headerandfooter_footer_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.CharField(help_text='The newsletter email', max_length=100)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.AlterField(
            model_name='headerandfooter',
            name='footer_image_url',
            field=models.URLField(blank=True, help_text="The Footer url - Don't Edit.", null=True),
        ),
        migrations.AlterField(
            model_name='headerandfooter',
            name='header_image_url',
            field=models.URLField(blank=True, help_text="The header url - Don't Edit.", null=True),
        ),
    ]
