# Generated by Django 4.2.4 on 2023-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfmailapp', '0006_newsletter_alter_headerandfooter_footer_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='selfmailmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='selfmailmodel',
            name='file',
            field=models.ManyToManyField(blank=True, help_text='A pdf you want to send.', null=True, to='selfmailapp.filemodel'),
        ),
    ]
